config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :comments, only: [:create, :edit, :update]
  end
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :text, presence: true, unless: :score?
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    
    def create
      @comment = @post.comments.new(comment_params) 
      @comment.save if user_signed_in? 
      redirect_to post_path(@post)
    end

    def update
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        respond_to do |format|
          format.html { redirect_to root_path }
          format.json
        end
      end
    end
    private
    def comment_params
      params.require(:comment).permit(:text, :score).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find(params[:post_id])  
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :move_to_index, except: [:index,:show]
  before_action :set_post, only: [:destroy, :edit, :update, :show]
  before_action :set_sort_type, only:[:index, :show,]
  
    def index
      @sort = "P_I"
      case @sort_type
        when "score"
          @posts = Post.order("created_at DESC").includes(:user).page(params[:page]).per(5)
        when "comments"
          @posts = Post.order("created_at DESC").includes(:user).page(params[:page]).per(5)
        else
          @posts = Post.order("created_at DESC").includes(:user).page(params[:page]).per(5)
      end
      
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.text.present?
        if @post.save
          redirect_to root_path
        else
          redirect_to :back 
        end
      else
        redirect_to :back 
      end
    
    end

    def destroy
      if @post.user_id == current_user.id
        @post.destroy
        redirect_to :back 
      end
    end

    def edit
    end

    def update
      @post.update(post_params) if @post.user_id == current_user.id && @post.text.present?
      redirect_to root_path
    end

    def show
      @sort = "P_S"
      @comment = Comment.new
      @count = @post.comments.count
      @average = @post.comments.average(:score)
      case @sort_type
        when "score"
          @comments = @post.comments.order("score DESC").includes(:user).page(params[:page]).per(5)
        when "comments"
          @comments = @post.comments.order("created_at DESC").includes(:user).page(params[:page]).per(5)
        else
          @comments = @post.comments.order("created_at DESC").includes(:user).page(params[:page]).per(5)
      end
    end


    private
    def post_params
      params.require(:post).permit(:text).merge(user_id: current_user.id)
    end
    

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

    def set_post
      @post = Post.find(params[:id])
    end
  
    def set_sort_type
      @sort_type = params[:sort_type]
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @sort_type = params[:sort_type]
    @sort = "U_S"
    @user = User.find(params[:id])
    @count = @user.posts.count
    case @sort_type
      when "score"
        @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
      when "comments"
        @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
      else
        @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MINI_MINI_APP
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    
    -# %link(rel="stylesheet" hfef="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css")
    
    -# %script(src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js")

    -# %script(src="https://code.jquery.com/jquery-3.3.1.js"
    -#         integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    -#         crossorigin="anonymous")
  %body
    -# = render 'layouts/notifications'
    = yield

app/views/posts/_comment.html.haml
= form_for [@post, comment],html: {class:"comment"} do |f|
  .comment--info
    .comment--info__name     
      = "投稿者： #{comment.user.name}"
    .comment--info__date
      = "投稿日時： #{comment.created_at.strftime("%Y/%m/%d")}"
    .comment--info__score
      - if comment.score?
        #comment-score
          = "#{comment.score}点"
      - else
        #comment-score
          未評価
      =f.number_field :score, max: 100, min: 0, class: "edit--comment--score"
  .comment--text
    =f.text_field :text,value: "#{comment.text}", id: "autocomplete-input", class: "autocomplete edit--comment--text"
    - if comment.text?
      #text
        = comment.text
    - else
      コメントはありません
  -if user_signed_in? && comment.user.id == current_user.id 
    .comment--edit
      .waves-effect.waves-light.btn.edit--btn
        Edit
      = f.submit '送信',class: "waves-effect waves-light btn submit--btn", id: "submit--bottun"
     
      

app/views/posts/_form.html.haml
.row
  .wrap
    .form_title
      -if controller.action_name == "new"  
        post
      - else
        Edit
  = form_for @post, html: {class:"col s12"} do |f|
    .row
      .input-field.col.s12
        =f.text_area :text, class: "materialize-textarea", id: "textarea1",value: "#{@post.text}"
        =f.label :text do
          本文
    = f.submit '送信',class: "waves-effect waves-light btn"
    

app/views/posts/edit.html.haml
.wapper
  = render "shared/hedder"
  = render "form", locals: {post: @post}

app/views/posts/index.html.haml
.wapper
  = render "shared/hedder"
  .posts
    = render partial: 'shared/post', collection: @posts  
    = paginate(@posts)
.test
= @sort_type

app/views/posts/new.html.haml
.wapper
  = render "shared/hedder"
  = render "form"

app/views/posts/show.html.haml
.wapper
  = render "shared/hedder"
  .posts
    = render partial: 'shared/post', locals: {post: @post}
  - if user_signed_in? &&  @post.comments.find_by(user_id: current_user.id) == nil
    .comment--warp
      .comment--warp--form
        .row
          = form_for [@post, @comment], html: {class:"col s12"} do |f|
            .row
              .input-field.col.s12
                =f.text_field :text, id: "autocomplete-input", class: "autocomplete"
                =f.label :text do
                  コメント
              - unless @post.user_id == current_user.id
                #form--number  
                  =f.number_field :score, max: 100, min: 0
                  =f.label :score do
                    スコア
              #form--bottun
                = f.submit '送信',class: "waves-effect waves-light btn"
        
  .posts
    .comment--title
      %span.comment--title__text
        コメント一覧           
        -if @average
          = "平均#{@average}点"
        - else
          未評価です
      %span.comment--title__count
        = "全#{@count}件"
    .comments
      = render partial: 'comment', collection: @comments
      = paginate(@comments)

app/views/shared/_hedder.html.haml
%nav
  .nav-wrapper
    .brand-logo#logo
      =link_to "BLOG", root_path
    - if user_signed_in? 
      .nav-left.login
        =link_to "#{current_user.name}さんのマイページ", user_path(current_user)
    - else
      .nav-left
        =link_to "ログインしてください", new_user_session_path

    %ul.right.hide-on-med-and-down#nav-mobile.nav_lists
      - if user_signed_in? 
        %li
          =link_to "New", new_post_path
        %li
          =link_to "Singout", destroy_user_session_path, method: :delete
      - else
        %li
          =link_to "Singin", new_user_session_path
        %li
          =link_to "Singup", new_user_registration_path
      %li#setting_bottun
        %a
          Setting
%ul.collapsible
  %li.sub_menu
    .collapsible-header
      Font-size
      %span.badge
        +
    %li.sub_menu_content
      .collapsible-header
        %ul
          %li.font_size
            %label
              %input.font_type(name="group2" type="radio" value="small")
              %span 
                文字: 小 
          %li.font_size
            %label
              %input.font_type(name="group2" type="radio" value="midium"  checked="checked")
              %span 
                文字: 中
          %li.font_size      
            %label
              %input.font_type(name="group2" type="radio" value= "large")
              %span 
                文字: 大
      
  %li.sub_menu
    .collapsible-header
      Color
      %span.badge
        +
    %li.sub_menu_content
      .collapsible-header
        %ul
          %li.color_name
            %label
              %input.color_type(name="group1" type="radio" checked="checked" value ="default")
              %span 
                Default
              元に戻るよ
          %li.color_name      
            %label
              %input.color_type(name="group1" type="radio" value="blue")
              %span 
                BLUE
              青色になるよ
          %li.color_name      
            %label
              %input.color_type(name="group1" type="radio" value="green")
              %span 
                GREEN
              緑になるよ
  -if @sort.present?
    %li.sub_menu
      .collapsible-header
        Sort
        %span.badge
          +
      %li.sub_menu_content
        .collapsible-header
          %ul
            %li.sort
              %label
                %input.sort_type(name="group1" type="radio" checked="checked" value ="default")
                %span 
                  - case @sort
                    - when "P_I"
                      =link_to "日時", "?so.rt_type=new", sort_type: "new"
                    - when "P_S"
                      =link_to "日時", "./#{@post.id}?sort_type=new", sort_type: "new"
                    - when "U_S"
                      =link_to "日時", "./#{@user.id}?sort_type=new", sort_type: "new"
            %li.sort    
              %label
                %input.sort_type(name="group1" type="radio" value="blue")
                %span
                  - case @sort
                    - when "P_I"
                      =link_to "スコア" , ".?sort_type=score", sort_type: "score"
                    - when "P_S"
                      =link_to "スコア" , "./#{@post.id}?sort_type=score", sort_type: "score"   
                    - when "U_S"
                      =link_to "スコア" , "./#{@user.id}?sort_type=score", sort_type: "score"  
            - unless @sort == "P_S"
              %li.sort
                %label
                  %input.sort_type(name="group1" type="radio" value="green")
                  %span
                    - case @sort
                      - when "P_I"
                        =link_to "コメント数", ".?sort_type=comments", sort_type: "comments"
                      - when "P_S"
                        =link_to "コメント数", "./#{@post.id}?sort_type=comments", sort_type: "comments"
                      - when "U_S"
                        =link_to "コメント数", "./#{@user.id}?sort_type=comments", sort_type: "comments"
                        
                  

　        

app/views/shared/_post.html.haml
=link_to user_path(post.user), class: "card-name" do
  %span.name
    = post.user.name
  %span.plus
    さんの投稿

- average = post.comments.average(:score).to_i
- if average == 100
  -set_class = "card--reinbow"
- elsif average > 80
  -set_class = "card--gold"
- elsif average > 70
  -set_class = "card--silver"
- elsif average > 60
  -set_class = "card--bronze"
- elsif average == 0 && post.comments.average(:score)
  -set_class = "card--0"

 

.card{ class: "#{set_class}" }
  .card--content
    = post.text
  .card--buttons
    .waves-effect.waves-light.btn
      =link_to "Show", post_path(post)
    .card--average
      - if average != 0
        = "平均点#{average}"
      - elsif average == 0 && post.comments.average(:score)
        0点...
      - else
        未評価です
      
    .ooo
      = "コメント数 : #{post.comments.count}件"
      = "投稿日時: #{post.created_at.strftime("%Y/%m/%d %H:%M")}"
    - if user_signed_in? && current_user.id == post.user.id 
      .waves-effect.waves-light.btn
        =link_to "Edit", edit_post_path(post)
      .waves-effect.waves-light.btn#destroy
        =link_to "Destroy", "/posts/#{post.id}", method: :delete 
    
    
  

app/views/users/show.html.haml
.wapper
  = render "shared/hedder"
    
  
  .posts
    .user-page-title
      %span.user-page-title__name
        = @user.name
      %span.user-page-title__after
        = "さんの投稿です！(全#{@count}件)"

    = render partial: 'shared/post', collection: @posts  
    = paginate(@posts)